- id: branch-naming-hook
  name: Validate Branch Naming
  description: Enforces branch naming rules based on a regex pattern.
  entry: branch-naming-hook
  language: python
  pass_filenames: false
  args: ["ST"]  # Default project abbreviation (can be overridden in .pre-commit-config.yaml)
  stages: [pre-push]  # Use [commit] for pre-commit or [push] for pre-push
