- id: validate-branch-name
  name: Validate Branch Naming
  description: Enforces branch naming rules based on a regex pattern.
  entry: bash validate-branch.sh
  language: system
  pass_filenames: false
  args: ["ST"]  # Default project abbreviation (can be overridden in .pre-commit-config.yaml)
  stages: [push]  # Use [commit] for pre-commit or [push] for pre-push
