repos:
  - repo: https://github.com/billy-doyle/branch-naming-hook
    rev: v1.0.0
    hooks:
      - id: branch-naming-hook
        args: ["ST"]
        stages: ["pre-push"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format
